spring.application.name=NeuroFleetX


# PostgreSQL DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/neurofleetx
spring.datasource.username=postgres
spring.datasource.password=Subhadip@2003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=MySuperStrongSecretKeyThatIsAtLeast32Chars!
# 24 hours
jwt.expirationMs=86400000

# ML Service Configuration
ml.service.url=http://localhost:5001/api
ml.service.connect-timeout=5000
ml.service.read-timeout=10000

# Logging
logging.level.com.infosys.service.MLPredictionService=DEBUG
logging.level.org.springframework.web.client=DEBUG

# ========== SMTP EMAIL CONFIGURATION ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subhadipguchhait106@gmail.com
spring.mail.password=wqjt utah jonx qtvw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Application Settings
app.name=NeuroFleetX
app.url=http://localhost:5173
app.support.email=support@neurofleetx.com
app.noreply.email=no-reply@neurofleetx.com 

# Password Reset
password.reset.token.expiry=3600000


# ============ Booking Configuration ============
booking.default-price-per-hour=50.0
booking.ev-surcharge=2.0
booking.time-slot-duration-minutes=60

# Razorpay Payment Gateway Configuration
# ============================================
razorpay.key.id=rzp_test_IY5Zn2fjFizUvg
razorpay.key.secret=29ZHoqRpoCySp9mSFc7JH1R7

# ============ Maintenance Configuration ============
maintenance.check-interval-days=30
maintenance.critical-threshold=6
maintenance.due-threshold=3

# Logging
logging.level.com.infosys.service=INFO
logging.level.com.infosys.controller=INFO
logging.level.com.infosys.repository=DEBUG

REACT_APP_GOOGLE_MAPS_API_KEY=AIzaSyDIYCxWR2SzSGIyrQP9uJyNxycYenXjWkA
