export const VehicleActionTypes = {
  SET_VEHICLES: "SET_VEHICLES",
  UPDATE_VEHICLE: "UPDATE_VEHICLE",
  ADD_VEHICLE: "ADD_VEHICLE",
  DELETE_VEHICLE: "DELETE_VEHICLE",
  FILTER_BY_TYPE: "FILTER_BY_TYPE",
  FILTER_BY_STATUS: "FILTER_BY_STATUS",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
};
